### PR TITLE
Avoid unnecessary computation

### PR DESCRIPTION
**Pull request by JWhitleyAStuff**
Supersedes PR #155 - all work done by @facontidavide.

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
This has been tested by @pjreed and is working as expected on a VLP-32C and two VLP-16s. Going ahead and merging.

**Comment by facontidavide** [comment]
awesome

**Comment by JWhitleyAStuff** [comment]
@facontidavide - Thank you so much for these changes! I'm seeing an average reduction on my machine from ~40-43% on a single core to ~26% on a single core. Huge improvement!

**Comment by facontidavide** [comment]
You are welcome.  Saving the planet from global warming ;)

**Pull request merged**
