### PR TITLE
Update driver to better support for HDL-64E S3

### PR DESCRIPTION
**Pull request by jmlago91**
Update to satisfy exact packet rate provided by HDL-64E S3, according to manufacturer documentation.
This packet rate varies sligthly according to the spin rate.

### CODE REVIEW

**Comment by Ry0** [comment]
@jmlago91 Hello.
I commented because your pull request was interesting.
I have one question.
How did you get the number of points generated per second (1333120 points/sec) for the HDL 64e s3 in this commit 39452117da1ecfe701bfc579ae487dcffdd1ba73?
I could not find the exactly value in the HDL-64E S3 Manual.
http://velodynelidar.com/docs/manuals/63-HDL64ES3H%20MANUAL,USERS%20AND%20PROGRAM%20GUIDE,HDL-64E%20S3.pdf

Finally, I would like to know the number of points in Dual Return Mode as well.
I'd be grateful if you could give me the information.

**Comment by jmlago91** [comment]
Hi @Ry0 
In page 50 of Velodyne S3 manual you can find a table showing the points per revolution for 1 laser (2038 for 600rpm or 10Hz) at different spin rates. Since S3 has 64 lasers, for 600rpm:

                    `2038 point/laser/rev * 64 laser * 10 revs/sec = 1333120 points/sec`

Regardless, this is a workaround for the packet rate of the Velodyne, and not a final solution.
Packet rate of the Velodyne isn't a constant value and varies with the spin rate (that has a small variation with the temperature) so taking an exact data rate to divide the stream in frames causes problems like this: https://github.com/ros-drivers/velodyne/issues/116 among others.

Another approach could be to read the azimuth value for all packets to look for 0 and 35999, and publish a frame with the points of that packets.

**Comment by Ry0** [comment]
@jmlago91 I'm grateful for your immediate response.
I did not know that it was  derived by the simple calculation.
Thank you.

That issue was submitted by a member of the same laboratory:)
We also solved the problem of that issue in HDL-64E S3.
Though not completely confirmed, S3 was started up in Dual Return Mode(the number of point clouds will be larger than usual.), and the `packet_rate` was insufficient than usual.

[before] HDL-64E S3 @20Hz
https://www.youtube.com/watch?v=b_E3b2v2MDQ
[after] S3 worked almost perfectly with your pull request.
https://www.youtube.com/watch?v=FvqGzCRTpSE

Finally, I have a concerned part.
Is it not necessary to define the packet_rate for each model like the 600rpm?

`velodyne_driver/src/driver/driver.cc`
```diff
+
+  // Different packet rate based on rpm
+
+  if (config_.rpm != 600.0)
+    {
+      if (config_.rpm == 300.0 || config_.rpm == 900)
+        {
+        packet_rate = 3472.5;
+        }
+      else if (config_.rpm == 1200)
+        {
+        packet_rate = 3473.33;
+        }
+    }
+  
```

**Comment by jmlago91** [comment]
Hi again.

Yes, it will be necessary to define the packet rate for all the possible cases, but that code was only a workaround for the S3 that was the version that I had been working.
Nevertheless, as I said before the solution is to implement an azimuth-based driver.

**Comment by jack-oquin** [comment]
Thanks for  working on this, @jmlago91. 

I'd like to merge a fix for it, but the patch submitted here appears to break all the other models, if not running at 600 RPM. Am I missing something?

**Comment by jmlago91** [comment]
Hi @jack-oquin,

I'm no longer working with the Velodyne S3, but I remember that the exact packet rate is different for other models and rpm. It's neccesary to extend the fix to satisfy all posible models and rpm. I'm pretty sure the necessary info will be on the datasheet of the other models.

Best regards.

**Comment by mwhannan74** [comment]
Hi,

I know this thread is old, but I am working with a S3 version and cannot get it to work properly using this version of the driver. I get some of the data correctly, but I am getting both a blanking issue and more importantly a lot of incorrect rings close to the sensor (see image). Any help would be appreciated.

Thanks
Michael

velodyne_hdl64-s3_ros_error

**Comment by jmlago91** [comment]
See my answers here:
https://github.com/ros-drivers/velodyne/issues/106

Are you applying the correct calibration file?

**Comment by mwhannan74** [comment]
Thanks for the quick response. Yes, I applied the correct calibration file. Everything looks fine in veloview, but just not with ROS. I think there are 2 issues. 

1st, I had the min range set to 0.9 meters and once I changed it to 1.6m all of the rings seem to go away. I have the lidar sitting close to a lot of things in the lab and this could be the issue. I will take it outside and see if still works. 

2nd, reading the comments above the missing scans may be due to a packet rate issue. I will try different values of npackets and see what happens.

Thanks again

**Comment by mwhannan74** [comment]
I raised the sensor up off the floor, but I am still seeing the wall of rings inside 1.6 meter. He is some output from the velodyne driver when it starts up. Does it all look correct?

 * /velodyne_nodelet_manager_cloud/max_range: 130.0
 * /velodyne_nodelet_manager_cloud/min_range: 1.67
 * /velodyne_nodelet_manager_driver/frame_id: lidar
 * /velodyne_nodelet_manager_driver/model: 64E_S3
 * /velodyne_nodelet_manager_driver/read_fast: False
 * /velodyne_nodelet_manager_driver/read_once: False
 * /velodyne_nodelet_manager_driver/repeat_delay: 0.0
 * /velodyne_nodelet_manager_driver/rpm: 600.0

[ INFO] [1505137154.070383144]: laser_ring[38] =  0, angle = -0.429412
[ INFO] [1505137154.070417875]: laser_ring[39] =  1, angle = -0.421952
[ INFO] [1505137154.070450513]: laser_ring[42] =  2, angle = -0.412384
[ INFO] [1505137154.070482681]: laser_ring[43] =  3, angle = -0.402735
[ INFO] [1505137154.070506939]: laser_ring[32] =  4, angle = -0.391959
[ INFO] [1505137154.070517328]: laser_ring[33] =  5, angle = -0.386360
[ INFO] [1505137154.070553200]: laser_ring[36] =  6, angle = -0.376145
[ INFO] [1505137154.070576077]: laser_ring[37] =  7, angle = -0.370119
[ INFO] [1505137154.070605297]: laser_ring[40] =  8, angle = -0.360668
[ INFO] [1505137154.070616085]: laser_ring[41] =  9, angle = -0.349887
[ INFO] [1505137154.070626997]: laser_ring[46] = 10, angle = -0.337748
[ INFO] [1505137154.070637983]: laser_ring[47] = 11, angle = -0.330999
[ INFO] [1505137154.070648679]: laser_ring[50] = 12, angle = -0.323668
[ INFO] [1505137154.070659211]: laser_ring[51] = 13, angle = -0.315746
[ INFO] [1505137154.070669696]: laser_ring[54] = 14, angle = -0.305368
[ INFO] [1505137154.070680198]: laser_ring[55] = 15, angle = -0.296044
[ INFO] [1505137154.070690579]: laser_ring[44] = 16, angle = -0.286667
[ INFO] [1505137154.070701101]: laser_ring[45] = 17, angle = -0.278938
[ INFO] [1505137154.070711581]: laser_ring[48] = 18, angle = -0.270416
[ INFO] [1505137154.070722165]: laser_ring[49] = 19, angle = -0.263189
[ INFO] [1505137154.070732543]: laser_ring[52] = 20, angle = -0.252869
[ INFO] [1505137154.070743047]: laser_ring[53] = 21, angle = -0.241338
[ INFO] [1505137154.070753599]: laser_ring[58] = 22, angle = -0.230904
[ INFO] [1505137154.070764092]: laser_ring[59] = 23, angle = -0.223919
[ INFO] [1505137154.070774563]: laser_ring[62] = 24, angle = -0.217691
[ INFO] [1505137154.070785207]: laser_ring[63] = 25, angle = -0.208122
[ INFO] [1505137154.070795537]: laser_ring[34] = 26, angle = -0.199300
[ INFO] [1505137154.070805993]: laser_ring[35] = 27, angle = -0.188278
[ INFO] [1505137154.070816524]: laser_ring[56] = 28, angle = -0.180376
[ INFO] [1505137154.070826755]: laser_ring[57] = 29, angle = -0.171657
[ INFO] [1505137154.070837181]: laser_ring[60] = 30, angle = -0.162514
[ INFO] [1505137154.070847635]: laser_ring[61] = 31, angle = -0.155340
[ INFO] [1505137154.070858076]: laser_ring[ 6] = 32, angle = -0.150245
[ INFO] [1505137154.070868663]: laser_ring[ 7] = 33, angle = -0.144645
[ INFO] [1505137154.070879274]: laser_ring[10] = 34, angle = -0.138635
[ INFO] [1505137154.070889652]: laser_ring[11] = 35, angle = -0.132012
[ INFO] [1505137154.070900080]: laser_ring[ 0] = 36, angle = -0.125779
[ INFO] [1505137154.070910771]: laser_ring[ 1] = 37, angle = -0.120142
[ INFO] [1505137154.070921247]: laser_ring[ 4] = 38, angle = -0.115304
[ INFO] [1505137154.070931758]: laser_ring[ 5] = 39, angle = -0.108036
[ INFO] [1505137154.070942234]: laser_ring[ 8] = 40, angle = -0.103589
[ INFO] [1505137154.070952804]: laser_ring[ 9] = 41, angle = -0.097114
[ INFO] [1505137154.070963172]: laser_ring[14] = 42, angle = -0.089616
[ INFO] [1505137154.070973513]: laser_ring[15] = 43, angle = -0.084544
[ INFO] [1505137154.070983808]: laser_ring[18] = 44, angle = -0.078452
[ INFO] [1505137154.070994377]: laser_ring[19] = 45, angle = -0.072965
[ INFO] [1505137154.071004792]: laser_ring[22] = 46, angle = -0.067066
[ INFO] [1505137154.071015206]: laser_ring[23] = 47, angle = -0.061773
[ INFO] [1505137154.071025535]: laser_ring[12] = 48, angle = -0.054439
[ INFO] [1505137154.071035981]: laser_ring[13] = 49, angle = -0.049138
[ INFO] [1505137154.071046431]: laser_ring[16] = 50, angle = -0.043019
[ INFO] [1505137154.071056864]: laser_ring[17] = 51, angle = -0.037305
[ INFO] [1505137154.071067265]: laser_ring[20] = 52, angle = -0.031996
[ INFO] [1505137154.071077782]: laser_ring[21] = 53, angle = -0.026686
[ INFO] [1505137154.071088163]: laser_ring[26] = 54, angle = -0.018718
[ INFO] [1505137154.071098631]: laser_ring[27] = 55, angle = -0.012996
[ INFO] [1505137154.071108993]: laser_ring[30] = 56, angle = -0.008704
[ INFO] [1505137154.071119463]: laser_ring[31] = 57, angle = -0.002162
[ INFO] [1505137154.071129923]: laser_ring[ 2] = 58, angle = +0.003766
[ INFO] [1505137154.071140405]: laser_ring[ 3] = 59, angle = +0.008467
[ INFO] [1505137154.071150885]: laser_ring[24] = 60, angle = +0.016029
[ INFO] [1505137154.071161310]: laser_ring[25] = 61, angle = +0.021955
[ INFO] [1505137154.071171767]: laser_ring[28] = 62, angle = +0.028084
[ INFO] [1505137154.071182264]: laser_ring[29] = 63, angle = +0.033393
[ INFO] [1505137154.071512887]: Number of lasers: 64.
[ INFO] [1505137154.080564834]: Velodyne Convert: Reconfigure Request
[ INFO] [1505137154.122070920]: VelodyneDriver: rotating = 600 RPM = 10 Hz
[ INFO] [1505137154.122114561]: VelodyneDriver: packet rate = 3471.66 packets/sec
[ INFO] [1505137154.122536049]: VelodyneDriver: npackets = 348 packets/scan

**Comment by jmlago91** [comment]
Please attach a screenshot.
Also it would be useful to see the original calibration file provided by Velodyne.

**Comment by mwhannan74** [comment]
I have isolated the flickering and undersized point clouds, but not sure why it is happening. For some reason I am getting a repeat of all of the laser data for each angle. If I double the npackets and ignore the repeated blocks, then I get a full point cloud for the scan. I suspect that the lidar is in dual return mode, but I have sent the command to force the lidar to only use the strongest return. There is no way to verify that since the interface to the lidar does not give any acknowledgement. I tested using the rpm command and can get the lidar to change speed.

As for the lidar rings close to the sensor, I cannot determine why they exist. I checked the calibration angles in veloview with those printed out from ROS and they are the same. I can remove them from the point cloud by setting the min range to 1.58 meters, but that only seems like a temporary fix.

Any thoughts?


[ INFO] [1505220829.972689114]: Velodyne RawData: Unpacking packet for laser # = 62 @ angle = 321.120000
[ INFO] [1505220829.972752638]: Velodyne RawData: Unpacking packet for laser # = 63 @ angle = 321.120000
[ INFO] [1505220829.972786939]: Velodyne RawData: Unpacking packet for laser # = 0 @ angle = 321.390000
[ INFO] [1505220829.972824683]: Velodyne RawData: Unpacking packet for laser # = 1 @ angle = 321.390000
[ INFO] [1505220829.972884256]: Velodyne RawData: Unpacking packet for laser # = 2 @ angle = 321.390000
[ INFO] [1505220829.972920016]: Velodyne RawData: Unpacking packet for laser # = 3 @ angle = 321.390000
[ INFO] [1505220829.972960556]: Velodyne RawData: Unpacking packet for laser # = 4 @ angle = 321.390000
[ INFO] [1505220829.973003671]: Velodyne RawData: Unpacking packet for laser # = 5 @ angle = 321.390000
[ INFO] [1505220829.973039903]: Velodyne RawData: Unpacking packet for laser # = 6 @ angle = 321.390000
[ INFO] [1505220829.973076824]: Velodyne RawData: Unpacking packet for laser # = 7 @ angle = 321.390000
[ INFO] [1505220829.973120715]: Velodyne RawData: Unpacking packet for laser # = 8 @ angle = 321.390000
[ INFO] [1505220829.973158201]: Velodyne RawData: Unpacking packet for laser # = 9 @ angle = 321.390000
[ INFO] [1505220829.973185809]: Velodyne RawData: Unpacking packet for laser # = 10 @ angle = 321.390000
[ INFO] [1505220829.973235980]: Velodyne RawData: Unpacking packet for laser # = 11 @ angle = 321.390000
[ INFO] [1505220829.973276658]: Velodyne RawData: Unpacking packet for laser # = 12 @ angle = 321.390000
[ INFO] [1505220829.973308072]: Velodyne RawData: Unpacking packet for laser # = 13 @ angle = 321.390000
[ INFO] [1505220829.973350842]: Velodyne RawData: Unpacking packet for laser # = 14 @ angle = 321.390000
[ INFO] [1505220829.973384908]: Velodyne RawData: Unpacking packet for laser # = 15 @ angle = 321.390000
[ INFO] [1505220829.973413687]: Velodyne RawData: Unpacking packet for laser # = 16 @ angle = 321.390000
[ INFO] [1505220829.973437634]: Velodyne RawData: Unpacking packet for laser # = 17 @ angle = 321.390000
[ INFO] [1505220829.973452728]: Velodyne RawData: Unpacking packet for laser # = 18 @ angle = 321.390000
[ INFO] [1505220829.973468944]: Velodyne RawData: Unpacking packet for laser # = 19 @ angle = 321.390000
[ INFO] [1505220829.973483319]: Velodyne RawData: Unpacking packet for laser # = 20 @ angle = 321.390000
[ INFO] [1505220829.973500092]: Velodyne RawData: Unpacking packet for laser # = 21 @ angle = 321.390000
[ INFO] [1505220829.973517194]: Velodyne RawData: Unpacking packet for laser # = 22 @ angle = 321.390000
[ INFO] [1505220829.973531181]: Velodyne RawData: Unpacking packet for laser # = 23 @ angle = 321.390000
[ INFO] [1505220829.973543234]: Velodyne RawData: Unpacking packet for laser # = 24 @ angle = 321.390000
[ INFO] [1505220829.973554384]: Velodyne RawData: Unpacking packet for laser # = 25 @ angle = 321.390000
[ INFO] [1505220829.973566603]: Velodyne RawData: Unpacking packet for laser # = 26 @ angle = 321.390000
[ INFO] [1505220829.973577922]: Velodyne RawData: Unpacking packet for laser # = 27 @ angle = 321.390000
[ INFO] [1505220829.973586806]: Velodyne RawData: Unpacking packet for laser # = 28 @ angle = 321.390000
[ INFO] [1505220829.973597717]: Velodyne RawData: Unpacking packet for laser # = 29 @ angle = 321.390000
[ INFO] [1505220829.973606719]: Velodyne RawData: Unpacking packet for laser # = 30 @ angle = 321.390000
[ INFO] [1505220829.973616352]: Velodyne RawData: Unpacking packet for laser # = 31 @ angle = 321.390000
[ INFO] [1505220829.973626250]: Velodyne RawData: Unpacking packet for laser # = 32 @ angle = 321.390000
[ INFO] [1505220829.973634986]: Velodyne RawData: Unpacking packet for laser # = 33 @ angle = 321.390000
[ INFO] [1505220829.973643518]: Velodyne RawData: Unpacking packet for laser # = 34 @ angle = 321.390000
[ INFO] [1505220829.973652373]: Velodyne RawData: Unpacking packet for laser # = 35 @ angle = 321.390000
[ INFO] [1505220829.973662176]: Velodyne RawData: Unpacking packet for laser # = 36 @ angle = 321.390000
[ INFO] [1505220829.973672135]: Velodyne RawData: Unpacking packet for laser # = 37 @ angle = 321.390000
[ INFO] [1505220829.973681947]: Velodyne RawData: Unpacking packet for laser # = 38 @ angle = 321.390000
[ INFO] [1505220829.973694935]: Velodyne RawData: Unpacking packet for laser # = 39 @ angle = 321.390000
[ INFO] [1505220829.973720618]: Velodyne RawData: Unpacking packet for laser # = 40 @ angle = 321.390000
[ INFO] [1505220829.973738363]: Velodyne RawData: Unpacking packet for laser # = 41 @ angle = 321.390000
[ INFO] [1505220829.973750194]: Velodyne RawData: Unpacking packet for laser # = 42 @ angle = 321.390000
[ INFO] [1505220829.973765842]: Velodyne RawData: Unpacking packet for laser # = 43 @ angle = 321.390000
[ INFO] [1505220829.973776448]: Velodyne RawData: Unpacking packet for laser # = 44 @ angle = 321.390000
[ INFO] [1505220829.973787646]: Velodyne RawData: Unpacking packet for laser # = 45 @ angle = 321.390000
[ INFO] [1505220829.973798069]: Velodyne RawData: Unpacking packet for laser # = 46 @ angle = 321.390000
[ INFO] [1505220829.973811474]: Velodyne RawData: Unpacking packet for laser # = 47 @ angle = 321.390000
[ INFO] [1505220829.973823163]: Velodyne RawData: Unpacking packet for laser # = 48 @ angle = 321.390000
[ INFO] [1505220829.973835137]: Velodyne RawData: Unpacking packet for laser # = 49 @ angle = 321.390000
[ INFO] [1505220829.973846026]: Velodyne RawData: Unpacking packet for laser # = 50 @ angle = 321.390000
[ INFO] [1505220829.973857306]: Velodyne RawData: Unpacking packet for laser # = 51 @ angle = 321.390000
[ INFO] [1505220829.973867094]: Velodyne RawData: Unpacking packet for laser # = 52 @ angle = 321.390000
[ INFO] [1505220829.973877735]: Velodyne RawData: Unpacking packet for laser # = 53 @ angle = 321.390000
[ INFO] [1505220829.973888123]: Velodyne RawData: Unpacking packet for laser # = 54 @ angle = 321.390000
[ INFO] [1505220829.973898914]: Velodyne RawData: Unpacking packet for laser # = 55 @ angle = 321.390000
[ INFO] [1505220829.973908861]: Velodyne RawData: Unpacking packet for laser # = 56 @ angle = 321.390000
[ INFO] [1505220829.973922973]: Velodyne RawData: Unpacking packet for laser # = 57 @ angle = 321.390000
[ INFO] [1505220829.973938539]: Velodyne RawData: Unpacking packet for laser # = 58 @ angle = 321.390000
[ INFO] [1505220829.973961987]: Velodyne RawData: Unpacking packet for laser # = 59 @ angle = 321.390000
[ INFO] [1505220829.973976812]: Velodyne RawData: Unpacking packet for laser # = 60 @ angle = 321.390000
[ INFO] [1505220829.973992986]: Velodyne RawData: Unpacking packet for laser # = 61 @ angle = 321.390000
[ INFO] [1505220829.974008286]: Velodyne RawData: Unpacking packet for laser # = 62 @ angle = 321.390000
[ INFO] [1505220829.974026543]: Velodyne RawData: Unpacking packet for laser # = 63 @ angle = 321.390000
[ INFO] [1505220829.974048442]: Velodyne RawData: Unpacking packet for laser # = 0 @ angle = 321.390000
[ INFO] [1505220829.974076444]: Velodyne RawData: Unpacking packet for laser # = 1 @ angle = 321.390000
[ INFO] [1505220829.974100435]: Velodyne RawData: Unpacking packet for laser # = 2 @ angle = 321.390000
[ INFO] [1505220829.974125813]: Velodyne RawData: Unpacking packet for laser # = 3 @ angle = 321.390000
[ INFO] [1505220829.974151471]: Velodyne RawData: Unpacking packet for laser # = 4 @ angle = 321.390000
[ INFO] [1505220829.974175584]: Velodyne RawData: Unpacking packet for laser # = 5 @ angle = 321.390000
[ INFO] [1505220829.974205455]: Velodyne RawData: Unpacking packet for laser # = 6 @ angle = 321.390000
[ INFO] [1505220829.974228828]: Velodyne RawData: Unpacking packet for laser # = 7 @ angle = 321.390000
[ INFO] [1505220829.974247314]: Velodyne RawData: Unpacking packet for laser # = 8 @ angle = 321.390000
[ INFO] [1505220829.974268479]: Velodyne RawData: Unpacking packet for laser # = 9 @ angle = 321.390000
[ INFO] [1505220829.974287748]: Velodyne RawData: Unpacking packet for laser # = 10 @ angle = 321.390000
[ INFO] [1505220829.974307919]: Velodyne RawData: Unpacking packet for laser # = 11 @ angle = 321.390000
[ INFO] [1505220829.974330407]: Velodyne RawData: Unpacking packet for laser # = 12 @ angle = 321.390000
[ INFO] [1505220829.974358228]: Velodyne RawData: Unpacking packet for laser # = 13 @ angle = 321.390000
[ INFO] [1505220829.974380837]: Velodyne RawData: Unpacking packet for laser # = 14 @ angle = 321.390000
[ INFO] [1505220829.974414621]: Velodyne RawData: Unpacking packet for laser # = 15 @ angle = 321.390000
[ INFO] [1505220829.974438654]: Velodyne RawData: Unpacking packet for laser # = 16 @ angle = 321.390000
[ INFO] [1505220829.974463877]: Velodyne RawData: Unpacking packet for laser # = 17 @ angle = 321.390000
[ INFO] [1505220829.974485640]: Velodyne RawData: Unpacking packet for laser # = 18 @ angle = 321.390000
[ INFO] [1505220829.974508423]: Velodyne RawData: Unpacking packet for laser # = 19 @ angle = 321.390000
[ INFO] [1505220829.974531030]: Velodyne RawData: Unpacking packet for laser # = 20 @ angle = 321.390000
[ INFO] [1505220829.974551674]: Velodyne RawData: Unpacking packet for laser # = 21 @ angle = 321.390000
[ INFO] [1505220829.974592168]: Velodyne RawData: Unpacking packet for laser # = 22 @ angle = 321.390000
[ INFO] [1505220829.974615237]: Velodyne RawData: Unpacking packet for laser # = 23 @ angle = 321.390000
[ INFO] [1505220829.974636544]: Velodyne RawData: Unpacking packet for laser # = 24 @ angle = 321.390000
[ INFO] [1505220829.974653087]: Velodyne RawData: Unpacking packet for laser # = 25 @ angle = 321.390000
[ INFO] [1505220829.974681235]: Velodyne RawData: Unpacking packet for laser # = 26 @ angle = 321.390000
[ INFO] [1505220829.974704203]: Velodyne RawData: Unpacking packet for laser # = 27 @ angle = 321.390000
[ INFO] [1505220829.974729258]: Velodyne RawData: Unpacking packet for laser # = 28 @ angle = 321.390000
[ INFO] [1505220829.974752280]: Velodyne RawData: Unpacking packet for laser # = 29 @ angle = 321.390000
[ INFO] [1505220829.974784319]: Velodyne RawData: Unpacking packet for laser # = 30 @ angle = 321.390000
[ INFO] [1505220829.974816476]: Velodyne RawData: Unpacking packet for laser # = 31 @ angle = 321.390000
[ INFO] [1505220829.974840751]: Velodyne RawData: Unpacking packet for laser # = 32 @ angle = 321.390000
[ INFO] [1505220829.974870511]: Velodyne RawData: Unpacking packet for laser # = 33 @ angle = 321.390000
[ INFO] [1505220829.975076187]: Velodyne RawData: Unpacking packet for laser # = 34 @ angle = 321.390000
[ INFO] [1505220829.975188032]: Velodyne RawData: Unpacking packet for laser # = 35 @ angle = 321.390000
[ INFO] [1505220829.975220948]: Velodyne RawData: Unpacking packet for laser # = 36 @ angle = 321.390000
[ INFO] [1505220829.975418134]: Velodyne RawData: Unpacking packet for laser # = 37 @ angle = 321.390000
[ INFO] [1505220829.975432653]: Velodyne RawData: Unpacking packet for laser # = 38 @ angle = 321.390000
[ INFO] [1505220829.975443637]: Velodyne RawData: Unpacking packet for laser # = 39 @ angle = 321.390000
[ INFO] [1505220829.975455644]: Velodyne RawData: Unpacking packet for laser # = 40 @ angle = 321.390000
[ INFO] [1505220829.975467336]: Velodyne RawData: Unpacking packet for laser # = 41 @ angle = 321.390000
[ INFO] [1505220829.975479032]: Velodyne RawData: Unpacking packet for laser # = 42 @ angle = 321.390000
[ INFO] [1505220829.975492525]: Velodyne RawData: Unpacking packet for laser # = 43 @ angle = 321.390000
[ INFO] [1505220829.975505812]: Velodyne RawData: Unpacking packet for laser # = 44 @ angle = 321.390000
[ INFO] [1505220829.975517670]: Velodyne RawData: Unpacking packet for laser # = 45 @ angle = 321.390000
[ INFO] [1505220829.975530787]: Velodyne RawData: Unpacking packet for laser # = 46 @ angle = 321.390000
[ INFO] [1505220829.975542889]: Velodyne RawData: Unpacking packet for laser # = 47 @ angle = 321.390000
[ INFO] [1505220829.975556708]: Velodyne RawData: Unpacking packet for laser # = 48 @ angle = 321.390000
[ INFO] [1505220829.975567544]: Velodyne RawData: Unpacking packet for laser # = 49 @ angle = 321.390000
[ INFO] [1505220829.975578560]: Velodyne RawData: Unpacking packet for laser # = 50 @ angle = 321.390000
[ INFO] [1505220829.975589917]: Velodyne RawData: Unpacking packet for laser # = 51 @ angle = 321.390000
[ INFO] [1505220829.975601207]: Velodyne RawData: Unpacking packet for laser # = 52 @ angle = 321.390000
[ INFO] [1505220829.975612737]: Velodyne RawData: Unpacking packet for laser # = 53 @ angle = 321.390000
[ INFO] [1505220829.975624979]: Velodyne RawData: Unpacking packet for laser # = 54 @ angle = 321.390000
[ INFO] [1505220829.975638125]: Velodyne RawData: Unpacking packet for laser # = 55 @ angle = 321.390000
[ INFO] [1505220829.975648570]: Velodyne RawData: Unpacking packet for laser # = 56 @ angle = 321.390000
[ INFO] [1505220829.975659436]: Velodyne RawData: Unpacking packet for laser # = 57 @ angle = 321.390000
[ INFO] [1505220829.975670449]: Velodyne RawData: Unpacking packet for laser # = 58 @ angle = 321.390000
[ INFO] [1505220829.975681092]: Velodyne RawData: Unpacking packet for laser # = 59 @ angle = 321.390000
[ INFO] [1505220829.975693057]: Velodyne RawData: Unpacking packet for laser # = 60 @ angle = 321.390000
[ INFO] [1505220829.975706262]: Velodyne RawData: Unpacking packet for laser # = 61 @ angle = 321.390000
[ INFO] [1505220829.975717723]: Velodyne RawData: Unpacking packet for laser # = 62 @ angle = 321.390000
[ INFO] [1505220829.975728135]: Velodyne RawData: Unpacking packet for laser # = 63 @ angle = 321.390000
[ INFO] [1505220829.975740637]: Velodyne RawData: Unpacking packet for laser # = 0 @ angle = 321.570000
[ INFO] [1505220829.975751086]: Velodyne RawData: Unpacking packet for laser # = 1 @ angle = 321.570000

**Comment by mwhannan74** [comment]
Veloview screen shot
veloview_velodynehdl64s3

**Comment by mwhannan74** [comment]
rviz screenshot
rviz_velodynehdl64s3_rings

**Comment by jmlago91** [comment]
I can't look at this in detail now, but everything seems normal since the lidar it's in dual return mode.

That weird circles arround de center are normal. Effectively you have to set the min range to 1.58 (or more dependibg the unit) since the APD detectors have a noise threshold that limits the useful minimum range.
In my unit min range is 1.62m.

**Comment by mwhannan74** [comment]
Thanks for you reply. Clipping at 1.58 seems to work fine and looks like a good fix for now. I am perplexed by the repeated data though. I will dig into it and see what I can find out. I have a hack to make it work for now, but I expect that I am only getting half the data rate since it is repeated.

**Comment by mwhannan74** [comment]
I wanted to come back to this to help any other people out that have these problems.

1) **Dual return mode issues.** This was due to the model that we purchased being a dual return model and not a single return model. The manual leads you to believe that you can switch between modes via serial commands, but that is not entirely true. If you set the unit to strongest mode, the sensor will still output data like it is in dual return mode. That means that you get a duplicate set of data. The manual seems to state that you should only get one, but after a forever back and forth with Velodyne this is not true.

2) **Data within 1.58 meters.** This is a bug with ROS code's conversion from raw distance to corrected distance. The issue is lasers that do not strike an object return dist=0 and intensity=1. In the code, the conversion from dist = 0 ends up with data in the 1.1 to 1.6 meter range. The solution is to catch the special case and not do the conversion.

In dealing with these issues, I made a slew of changes to the ROS Velodyne code for the S3 model. If any one is interested let me know. Here is some of the things I enhanced or fixed.
- Fixed issue with the wrong number of packets per revolution depending on speed of lidar. I moved some code from the rawdata.cc file to parse out the rotation angle. I now set a max number of packets, and then create a cloud based on one revolution.
- As noted above, fixed bug with "out of range" laser measurements
- As noted above, added support for dual range mode
- I also added parsing code for the status, warnings, and packet cycle #. 
- I also fixed some documentation and variable names that were wrong in the packet parsing code structs.

**Comment by aditya369007** [comment]
That sounds really awesome. I am interested to see and try your changes.

**Comment by JWhitleyAStuff** [comment]
@mwhannan74 - Please make a separate pull request so we can review/discuss the changes you have. This thread has gotten stale and is for an older set of changes that appears to break things. I've just begun maintaining this repo and I'd like to see the additions you're making included in a new release. Thanks.

**Pull request closed without merging**
