### PR TITLE
Updating maintainer email address.

### PR DESCRIPTION
**Pull request by wep21**
A part of #434

### CODE REVIEW

**Comment by wep21** [comment]
@JWhitleyWork please let me know if you have a new e-mail address.

**Comment by JWhitleyWork** [comment]
I do. I am no longer with the Autoware Foundation. However, I will continue to maintain my consulting business so the email address you can use is whitleysoftwareservices@gmail.com.

**Comment by wep21** [comment]
@JWhitleyWork update at https://github.com/ros-drivers/velodyne/pull/450/commits/13dd1a62a411890c88a7415e83f975c171393b0c

**Review by JWhitleyWork — APPROVED** [review]
Thanks!

**Pull request merged**
