### PR TITLE
[#121] Make PCL wrapper compatible with template classes

### PR DESCRIPTION
**Pull request by cglwn**
This adds the needed includes to interoperate with approximate k-Nearest Neighbours, using PCLBase, and Passthrough filters in PCL.

### CODE REVIEW

**Comment by jack-oquin** [comment]
Thanks for the contribution. 

I wonder if there is some way to fix the original problem without adding dependencies on several other PCL components?

**Comment by jack-oquin** [comment]
Would it work to put ``PCL_NO_PRECOMPILE`` and those other includes *before* the include of ``velodyne_pointcloud/point_types.h``?

**Comment by cglwn** [comment]
I'm not currently working on anything requiring this at the moment, but I will try it out when I get the chance.

**Comment by JWhitleyAStuff** [comment]
Closing due to inactivity.

**Pull request closed without merging**
