### PR TITLE
Add per point time field

### PR DESCRIPTION
**Pull request by wep21**
ros2 porting for #290
a part of #434

### CODE REVIEW

**Comment by wep21** [comment]
cc @JWhitleyWork @clalancette

**Comment by wep21** [comment]
@clalancette @JWhitleyWork friendly ping

**Comment by wep21** [comment]
@clalancette @JWhitleyWork friendly ping

**Comment by JWhitleyWork** [comment]
@wep21 Sorry for taking so long to get back to you. I believe this field should be added in a new point cloud container - something like `PointXYZIRT`. If it is added to the existing container, it will cause issues with data that were recorded using the existing point structure.

**Comment by wep21** [comment]
@JWhitleyWork I will rename `PointXYZIR` `PointXYZIRT` in https://github.com/ros-drivers/velodyne/pull/434/commits/749d3bb5c9a63aeae091aedc7301b3dc12efcd65. Is it enough for your suggestion?

**Comment by JWhitleyWork** [comment]
That should be fine. Please make sure to rename everywhere in the code.

**Comment by wep21** [comment]
@JWhitleyWork rename at https://github.com/ros-drivers/velodyne/pull/440/commits/3d529c523f17b538c8e0a07cd4039059960f57b2

**Comment by JWhitleyWork** [comment]
FYI - I'm not a fan of the fact that this PR introduces two changes - one for the time field and one for making `model` a new, required parameter. Please separate these into separate PRs in the future. Since this is going to the `ros2` branch, which is basically targeted at Rolling at this point, I'm willing to let it slide for now.

**Review by JWhitleyWork — APPROVED** [review]

**Pull request merged**
