### PR TITLE
Sign inversion in some equations

### PR DESCRIPTION
**Pull request by pomerlef**
I had to reverse engineered your driver for some calibration and, when expressing your equations with rotation matrix, realized that some signs were inverted. I could send you the equations but it's also consistent with the following:
- [Velodyne manual](http://www.velodynelidar.com/lidar/products/manual/HDL-64E%20S3%20manual.pdf) p. 44

 ```
xyDistance = distance * cosVertAngle;// — vOffsetCorr * sinVertAngle;
```

- this [calibration paper](http://cdn.intechweb.org/pdfs/23811.pdf), eq. (4)

### CODE REVIEW

**Comment by jack-oquin** [comment]
Thanks for the contribution.

Your interpretation looks right to me. That calculation had been added last year by "Kun Li ", who is not currently reachable via github messages.

Why do you suppose that ``// - vOffsetCorr`` expression is shown in the doc as a comment, and not as part of the code?

**Comment by pomerlef** [comment]
Not clear why they went into the trouble of putting it in a comment. This part ` - vOffsetCorr * sinVertAngle;` is only present in their latest documentation version. Maybe people pointed out that it was an approximation without it and they are slowly including it.

Those kind of missing elements start to make a difference with large distances. What is sure is that the parts added by "Kun Li" are mathematically correct. There was just a typo I guess.

**Comment by pomerlef** [comment]
Is there anything I can do for the rest?

**Comment by jack-oquin** [comment]
Not that I can think of, I've been busy on other projects and had no time for Velodyne work lately.

**Pull request merged**
