### PR TITLE
Fix pr 80

### PR DESCRIPTION
**Pull request by wjwwood**
See: https://github.com/ros-drivers/velodyne/pull/80#discussion_r55913000

I've also built this one on top of https://github.com/ros-drivers/velodyne/pull/81. If you guys decide you don't want travis-ci then I can rebase this.

I tested this one (running the tests and my file) on my mac with yaml-cpp 0.3 and on my Trusty VM using yaml-cpp 0.5.

Sorry for the mistake in #80.

### CODE REVIEW

**Comment by wjwwood** [comment]
Ok, travis is finally passing.

**Comment by jack-oquin** [comment]
No problem. 

I especially appreciate the Travis tests. If I'd known how to do it properly, or had time to figure it out, I would have added that long ago.

**Comment by jack-oquin** [comment]
Will: can you send me a copy of the calibration data that demonstrates the original problem?

**Comment by wjwwood** [comment]
I don't know for certain, as it isn't our sensor, but I can ask on Monday. I think there's a very good chance I can though.

**Comment by jack-oquin** [comment]
It's just their ``db.xml`` calibration file, right?

**Comment by wjwwood** [comment]
Yeah, we converted their `.xml` file using the tool in this repository. I can probably share both the `.xml` and the `.yaml`. I just don't have them with me.

**Comment by jack-oquin** [comment]
That would be great. I like to collect test data for as many bug fixes as possible.

**Comment by wjwwood** [comment]
@jack-oquin I got both the original xml file that we converted using the script in this repository and the output yaml file we got after running it:

https://gist.github.com/wjwwood/5b78d375495b19c77e8b

We had to modify the yaml file to change all `min_intensity` and `max_intensity` fields to have integers and not floats without my change.

**Comment by jack-oquin** [comment]
That's great. Thanks again!

**Pull request merged**
