### PR TITLE
support for multiple velodynes (improved)

### PR DESCRIPTION
**Pull request by bricerebsamen**
This is an improvement on @ddillenberger implementation of the multi velodyne support. From what I understand from his design, and from what I experienced today on my setup (4 16-beam velodynes), @ddillenberger code allows to read data from one and only one laser at the same time.

With this pull request, we add support for reading data simultaneously from several lidars at the same time. Each lidar must be configured with a separate IP address and to broadcast on a separate port.

With this code, we were able to read from 4 velodyne at the same time.

Credits also go to @ddillenberger and @ahendrix for this pull request.

### CODE REVIEW

**Comment by bricerebsamen** [comment]
I forgot to mention: compared to @ddillenberger implementation, we added a parameter for the udp port to read from.

**Comment by bricerebsamen** [comment]
This has been running with success on our system for quite some time already.

**Comment by jack-oquin** [comment]
Good to know, Brice.

Sorry I have been so slow to work on this driver. I am not actively using it myself these days. 

Would you be interested in being a co-maintainer?

**Comment by bricerebsamen** [comment]
OK. But I'm not using it much either. I have access to a few Pucks and a 64.
However, I'm using custom code for converting to a point cloud, because I'm using a different calibration file. So I would not be able to do much testing...

**Comment by jack-oquin** [comment]
Is your calibration method proprietary, or would you be interested in sharing it?

**Comment by bricerebsamen** [comment]
it's proprietary. 

The good news is that for the Pucks, it we don't need a calibration file.

**Comment by bricerebsamen** [comment]
@jack-oquin OK I'll volunteer to be a maintainer

**Comment by jack-oquin** [comment]
I appreciate your help.

**Pull request merged**
