### PR TITLE
Dashing fixes

### PR DESCRIPTION
**Pull request by clalancette**
This PR has a bunch of fixes that I needed to make the current Dashing actually work with my VLP-16.  With all of these in place, I'm now able to make this produce pointclouds as before.  @JWhitleyAStuff  please take a look, thanks!

### CODE REVIEW

**Comment by JWhitleyAStuff** [comment]
@clalancette - Everything in this MR looks fine. Do you know if it solves the problem that @pjreed brought up in #298?

**Comment by clalancette** [comment]
> @clalancette - Everything in this MR looks fine. Do you know if it solves the problem that @pjreed brought up in #298?

I believe it should, but a confirmation would be great.

**Comment by pjreed** [comment]
Yep, I just tested it out and it looks much better now.  Thanks!

**Comment by clalancette** [comment]
> Yep, I just tested it out and it looks much better now. Thanks!

Fantastic, thanks for testing!

**Pull request merged**
